name: Run Kafka Tests
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install docker
        run: |
          brew install docker docker-machine docker-compose
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Stop docker-compose
        run: docker-compose down