name: Run Kafka Tests
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install docker
        run: |
          brew install docker docker-machine docker-compose
          sudo docker –version
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Start docker-compose
        run: docker-compose up -d

      - name: Stop docker-compose
        run: docker-compose down